# Generated by Django 3.1.7 on 2021-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
